RGBLIGHT_ENABLE    = no
RGB_MATRIX_ENABLE  = yes
MOUSEKEY_ENABLE    = yes
NKRO_ENABLE        = yes
OLED_ENABLE        = yes
OLED_DRIVER        = SSD1306
LTO_ENABLE         = yes
EXTRAKEY_ENABLE 	= yes 
TAP_DANCE_ENABLE 	= yes
LTO_ENABLE      	= yes
VIA_ENABLE          = no         # Enable VIA
